import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import { Orbitron } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400",
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: "400",
});

// * This is how we use local fonts in NextJS
const myFont = localFont({
  src: "../../public/fonts/neotech.ttf",
  weight: "400",
  style: "normal",
  variable: "--font-neotech",
});

export const metadata = {
  title: "Abhinav Shrivastav",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Correctly specify the favicon path
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${orbitron.variable}`}>
        {children}
      </body>
    </html>
  );
}
